name: deploy - development
on:
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: Setup Node.js 20.x
        uses: actions/setup-node@master
        with:
          node-version: "20.x"

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Build app
        run: |
          npm run build

      - name: Create or update release directory
        uses: appleboy/ssh-action@master
        with:
          host: 52.57.211.196
          username: ubuntu
          key: ${{ secrets.PEM_FILE_DEV }}
          script: |
            RELEASE_DIR=~/releases/release_back
            mkdir -p $RELEASE_DIR

      - name: Transfer files to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: 52.57.211.196
          username: ubuntu
          key: ${{ secrets.PEM_FILE_DEV }}
          source: "build/"
          target: "~/releases/release_back"

      - name: Create symbolic link
        uses: appleboy/ssh-action@master
        with:
          host: 52.57.211.196
          username: ubuntu
          key: ${{ secrets.PEM_FILE_DEV }}
          script: |
            RELEASE_DIR=~/releases/release_back
            sudo ln -nfs $RELEASE_DIR/build /home/ubuntu/back
