name: deploy - development
on:
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: Setup Node.js 20.x
        uses: actions/setup-node@master
        with:
          node-version: "20.x"

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Build app
        run: |
          npm run build

      - name: Reload pm2 server
        # if: ${{ success() }}
        run: |
          pm2 reload server
          pm2 status
